DROP DATABASE IF EXISTS im;
CREATE DATABASE im;
GRANT ALL PRIVILEGES ON im.* TO 'im' @'%' IDENTIFIED BY 'im' ;
GRANT ALL PRIVILEGES ON im.* TO 'im' @'localhost' IDENTIFIED BY 'im' ;
ALTER SCHEMA im DEFAULT CHARACTER SET utf8mb4;
use im;